# Generated by Django 5.0.2 on 2024-03-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='started',
            new_name='created_at',
        ),
    ]
